name: 'Replace Value'
description: 'Replace a value in a file for the current run'
author: 'Visiosto oy'
inputs:
  file:
    description: 'The file where the content to replace is.'
    required: true
  replaced:
    description: 'The value that will be replaced.'
    required: true
  value:
    description: 'The value that the original value is replaced with.'
    required: true
  external-script:
    description: 'Whether or not to use the external script for replacing the value. Included to support some projects.'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - run: |
        echo "The inputs are:"
        echo "file: ${{ inputs.file }}"
        echo "replaced: ${{ inputs.replaced }}"
        echo "value: ${{ inputs.value }}"
        echo "external script: ${{ inputs.external-script }}"
        if [ "${{ inputs.external-script }}" = "true" ]; then
          chmod +x ${{ github.action_path }}/replace.sh
          ${{ github.action_path }}/replace.sh
        else
          sed -i -- "s/${{ inputs.replaced }}/${{ inputs.value }}/g" "${GITHUB_WORKSPACE}/${{ inputs.file }}"
          echo "The file is now:"
          cat ${{ inputs.file }}
          echo ""
        fi
      shell: bash
      env:
        FILE_TO_PROCESS: ${{ inputs.file }}
        VALUE_TO_REPLACE: ${{ inputs.replaced }}
        VALUE_TO_SET: ${{ inputs.value }}
branding:
  icon: 'edit-3'
  color: 'orange'
